//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioBoo.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioBoo.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boos.
        /// </summary>
        public static string BoosTitle {
            get {
                return ResourceManager.GetString("BoosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channel.
        /// </summary>
        public static string ChannelTitle {
            get {
                return ResourceManager.GetString("ChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to features.
        /// </summary>
        public static string FeaturedTitle {
            get {
                return ResourceManager.GetString("FeaturedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published.
        /// </summary>
        public static string MyBoosTitle {
            get {
                return ResourceManager.GetString("MyBoosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draft.
        /// </summary>
        public static string MyDraftBoosTitle {
            get {
                return ResourceManager.GetString("MyDraftBoosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now playing.
        /// </summary>
        public static string NowPlayingTitle {
            get {
                return ResourceManager.GetString("NowPlayingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseButton {
            get {
                return ResourceManager.GetString("PauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string RecordButton {
            get {
                return ResourceManager.GetString("RecordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record boo.
        /// </summary>
        public static string RecordTitle {
            get {
                return ResourceManager.GetString("RecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        public static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
    }
}
